# Update new version:
# - bump version number for the image below
# - run: 
#    $ sudo docker-compose down && sudo docker-compose up -d --force-recreate
version: '3'

services:
  gitlab-runner-container:
    image: gitlab/gitlab-runner:v15.3.0
    container_name: gitlab-runner-container
    restart: always
    volumes:
      - ./config/:/etc/gitlab-runner/
      - /var/run/docker.sock:/var/run/docker.sock
