version: "3"

networks:
  traefik_default:
    external: true

services:
  server:
    image: jeroenbourgois/homelab_mon:main
    container_name: homelab_mon
    env_file:
      - config/docker.env
    restart: always
    networks:
      - traefik_default
    ports:
      - "4000:4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homelab_mon.entrypoints=websecure"
      - "traefik.http.routers.homelab_mon.rule=host(`lab.jeroenbourgois.be`)"
      - "traefik.http.routers.homelab_mon.tls=true"
      - "traefik.http.routers.homelab_mon.tls.certresolver=staging"
      - "traefik.http.services.homelab_mon.loadbalancer.server.port=4000"
      - "traefik.http.routers.homelab_mon.middlewares=homelab_mon"
      - "traefik.http.middlewares.homelab_mon.basicauth.users=${BASIC_AUTH_PWD}"
